volumes:
  db-data:

networks:
  instavote:
    driver: bridge

services:
  vote:
    image: emmiduh93/vote:latest
    ports:
    - 5000:80
    depends_on:
      - redis
    networks:
    - instavote

  result:
    image: emmiduh93/result:latest
    ports:
    -  5001:4000
    depends_on:
      - db
    networks:
    - instavote

  worker:
    image: emmiduh93/worker:latest
    depends_on:
      - redis
      - db
    networks:
    - instavote

  redis:
    image: redis:alpine
    networks:
    - instavote

  db:
    image: postgres:9.4
    networks:
    - instavote
    volumes:
    - "db-data:/var/lib/postgresql/data"
    environment:
    - POSTGRES_HOST_AUTH_METHOD=trust
